### PR TITLE
fix(docs): add missing command to full node docker-compose.yaml example

### PR DESCRIPTION
**Pull request by lantelyes**
This adds the missing command parameter to the example docker-compose config, without this `docker-compose up` will not run as rundler needs a command specified

### CODE REVIEW

**Review by 0xfourzerofour — APPROVED** [review]
LGTM thanks for this

**Comment by 0xfourzerofour** [comment]
Before this can be merged can you change the commit message to comply with conventional commits standards?

https://www.conventionalcommits.org/en/v1.0.0/

**Review by 0xfourzerofour — CHANGES_REQUESTED** [review]
Please change commit message

**Comment by lantelyes** [comment]
> Please change commit message

@0xfourzerofour done!

**Comment by lantelyes** [comment]
@0xfourzerofour can this be merged? I think it could help over devs with getting up and running

**Pull request merged**
