### PR TITLE
fix: install ca certificate to the base ubuntu

### LINKED ISSUE #833: CA certificate issue in container with KMS signer mode
**Describe the bug**
Rundler process fails when executed within a container. Specifically, in my case, when running Rundler as a Kubernetes Pod, the following error is observed with the RUST_LOG=debug flag enabled:
```
  2024-10-08T16:20:27.517834Z  INFO rundler_builder::task: Using AWS KMS signer
    at crates/builder/src/task.rs:405

  2024-10-08T16:20:27.518054Z DEBUG log: with_native_roots processed 0 valid and 0 invalid certs

thread 'main' panicked at /cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-rustls-0.23.2/src/config.rs:48:9:
no CA certificates found
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**To reproduce**
Run Rundler in AWS KMS signer mode by specifying the BUILDER_AWS_KMS_KEY_IDS environment variable within a Docker container.

**Expected behavior**
The AWS KMS signer should be properly configured and operational when running inside a container.

For reference, a similar issue has been discussed on GitHub, such as in [this case](https://github.com/awslabs/aws-sdk-rust/discussions/434).

### PR DESCRIPTION
**Pull request by shunsukew**
Fixes #833 

## Proposed Changes
  - Add ca-certificates to the base ubuntu.

### CODE REVIEW

**Comment by 0xfourzerofour** [comment]
could you change your commit message to match the convential commit standards so it can pass the ci?

**Comment by shunsukew** [comment]
@0xfourzerofour 
Thank you for the comment, updated the commit message.

**Review by dancoombs — APPROVED** [review]

**Comment by dancoombs** [comment]
We require signed commits, see [here](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification) for details.

**Comment by shunsukew** [comment]
> We require signed commits, see [here](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification) for details.

Verified the commit, Thank you!

**Pull request merged**
